import { parse as parseYaml } from "jsr:@std/yaml@1";

const BEGIN_MARKER =
  "<!-- apm:readme:begin (generated by scripts/gen-skill-readme.ts — do not edit this block) -->";
const END_MARKER = "<!-- apm:readme:end -->";
const APM_NAMESPACE = "bigdra50/skills";

function repoRoot(): string {
  const cmd = new Deno.Command("git", {
    args: ["rev-parse", "--show-toplevel"],
    stdout: "piped",
    stderr: "null",
  });
  const { success, stdout } = cmd.outputSync();
  if (!success) throw new Error("not a git repository");
  return new TextDecoder().decode(stdout).trim();
}

function trackedSkillDirs(root: string): string[] {
  const cmd = new Deno.Command("git", {
    args: ["-C", root, "ls-files", "-z", "--", ":(glob)**/SKILL.md"],
    stdout: "piped",
    stderr: "null",
  });
  const { success, stdout } = cmd.outputSync();
  if (!success) throw new Error("git ls-files failed");
  return new TextDecoder()
    .decode(stdout)
    .split("\0")
    .filter((p) => p.length > 0)
    .filter((p) => !p.includes("/examples/"))
    .map((p) => p.replace(/\/SKILL\.md$/, ""))
    .sort();
}

function parseFrontmatter(
  path: string,
): Record<string, unknown> {
  const text = Deno.readTextFileSync(path);
  if (!text.startsWith("---\n")) {
    throw new Error(`${path}: missing frontmatter`);
  }
  const closing = text.indexOf("\n---", 4);
  if (closing === -1) {
    throw new Error(`${path}: unterminated frontmatter`);
  }
  return parseYaml(text.slice(4, closing)) as Record<string, unknown>;
}

function generatedBlock(
  name: string,
  description: string,
  apmId: string,
): string {
  const desc = description.trim().replace(/\s*\n\s*/g, " ");
  return `${BEGIN_MARKER}
# ${name}

> ${desc}

## Install

### APM (recommended)

\`\`\`bash
apm install ${apmId}
\`\`\`

Or declare it in \`apm.yml\` for a reproducible setup:

\`\`\`yaml
dependencies:
  apm:
    - ${apmId}
\`\`\`

then run \`apm install\`.

### Any agentskills.io-compatible agent

This is an [Agent Skills](https://agentskills.io) skill — a portable
\`SKILL.md\` folder that works with Claude Code, Codex, opencode, Gemini CLI,
Cursor, and other [compatible agents](https://agentskills.io/clients).

With the [\`skills\`](https://github.com/vercel-labs/skills) CLI (installs into
every detected agent's skills directory):

\`\`\`bash
npx skills add bigdra50/skills --skill ${name}
\`\`\`

Or copy the folder in directly:

\`\`\`bash
npx degit ${apmId} ~/.claude/skills/${name}
\`\`\`

See [SKILL.md](./SKILL.md) for what this skill does and when to use it.
${END_MARKER}`;
}

function render(existing: string | null, block: string): string {
  if (!existing || existing.trim().length === 0) {
    return `${block}\n`;
  }
  if (existing.includes(BEGIN_MARKER) && existing.includes(END_MARKER)) {
    const pre = existing.slice(0, existing.indexOf(BEGIN_MARKER));
    const post = existing.slice(
      existing.indexOf(END_MARKER) + END_MARKER.length,
    );
    return `${pre}${block}${post}`;
  }
  return `${block}\n\n${existing.trimStart()}`;
}

const checkMode = Deno.args.includes("--check");
const root = repoRoot();
const drift: string[] = [];
const skipped: string[] = [];

for (const dir of trackedSkillDirs(root)) {
  const absDir = `${root}/${dir}`;
  let fm: Record<string, unknown>;
  try {
    fm = parseFrontmatter(`${absDir}/SKILL.md`);
  } catch (e) {
    const msg = e instanceof Error ? e.message.split("\n")[0] : String(e);
    skipped.push(`${dir}/SKILL.md (${msg})`);
    continue;
  }

  const name = (fm.name as string) || dir.split("/").pop()!;
  const apmId = `${APM_NAMESPACE}/${dir}`;
  const readmePath = `${absDir}/README.md`;

  let existing: string | null = null;
  try {
    existing = Deno.readTextFileSync(readmePath);
  } catch {
    // file doesn't exist yet
  }

  const rendered = render(
    existing,
    generatedBlock(name, String(fm.description ?? ""), apmId),
  );

  if (existing === rendered) continue;

  if (checkMode) {
    drift.push(`${dir}/README.md`);
  } else {
    Deno.writeTextFileSync(readmePath, rendered);
    console.log(`synced ${dir}/README.md`);
  }
}

for (const s of skipped) {
  console.error(`skipped (unparseable frontmatter): ${s}`);
}

if (checkMode) {
  if (drift.length === 0) {
    console.log("all skill READMEs up to date");
  } else {
    console.error(
      "skill READMEs out of date (run `mise run gen:readme`):",
    );
    for (const p of drift) {
      console.error(`  ${p}`);
    }
    Deno.exit(1);
  }
}
