"""facts.py の仕様。本文の数値を、スクリプトの再実行で照合する。

実行: uv run --with pytest pytest docs/paper-report/scripts/facts_test.py
"""

from __future__ import annotations

import json
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from facts import main

HERE = Path(__file__).resolve().parent
TEMPLATE = HERE.parent / "templates" / "paper.tex"
# 渡した JSON ファイルの中身を、そのまま標準出力へ出すコマンド
EMIT = "import sys; print(open(sys.argv[1], encoding='utf-8').read())"


def emit_command(name: str) -> str:
    return f"{shlex.quote(sys.executable)} -c {shlex.quote(EMIT)} data/{name}.json"


def write_data(report: Path, name: str, values: dict) -> None:
    (report / "data").mkdir(exist_ok=True)
    (report / "data" / f"{name}.json").write_text(json.dumps(values, ensure_ascii=False), encoding="utf-8")


def make_report(report: Path, data: dict[str, dict], tex: str = "") -> Path:
    """data の名前ごとに JSON を書き、それを出力するコマンドを facts.json に並べる。"""
    commands = []
    for name, values in data.items():
        write_data(report, name, values)
        commands.append({"run": emit_command(name), "requires": [f"data/{name}.json"]})
    write_spec(report, commands)
    (report / "paper.tex").write_text(tex, encoding="utf-8")
    return report


def write_spec(report: Path, commands: list[dict]) -> None:
    (report / "facts.json").write_text(json.dumps({"commands": commands}), encoding="utf-8")


def invoke(capsys: pytest.CaptureFixture[str], *args: str) -> tuple[int, str]:
    code = main(["facts.py", *args])
    captured = capsys.readouterr()
    return code, captured.out + captured.err


def factdefs(report: Path) -> list[str]:
    text = (report / "facts.tex").read_text(encoding="utf-8")
    return [line for line in text.splitlines() if line.startswith("\\factdef")]


def test_update_はコマンドの順に_キーを並べた_facts_tex_を書く(tmp_path, capsys):
    report = make_report(tmp_path, {"b": {"lag-up": "267〜333", "gap": "5.80"}, "a": {"lag-tuned": 67}})
    code, _ = invoke(capsys, "update", str(report))
    assert code == 0
    assert factdefs(report) == [
        "\\factdef{gap}{5.80}",
        "\\factdef{lag-up}{267〜333}",
        "\\factdef{lag-tuned}{67}",
    ]
    text = (report / "facts.tex").read_text(encoding="utf-8")
    assert text.startswith("% Generated by facts.py")
    assert f"% run: {emit_command('b')}" in text


def test_tex_の特殊文字は_escape_して書く(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"share": "12 %", "name": "a_b", "cost": "$5 & #1"}})
    assert invoke(capsys, "update", str(report))[0] == 0
    assert set(factdefs(report)) == {
        "\\factdef{share}{12 \\%}",
        "\\factdef{name}{a\\_b}",
        "\\factdef{cost}{\\$5 \\& \\#1}",
    }


@pytest.mark.parametrize("value", ["\\textbf{x}", "{x}", "a~b", "x^2", "two\nlines"])
def test_tex_の命令になる文字を含む値は拒む(tmp_path, capsys, value):
    report = make_report(tmp_path, {"a": {"bad": value}})
    code, out = invoke(capsys, "update", str(report))
    assert code == 1
    assert "bad" in out
    assert not (report / "facts.tex").exists()


@pytest.mark.parametrize("value", [True, None, [1], {"x": 1}])
def test_値は文字列か数に限る(tmp_path, capsys, value):
    report = make_report(tmp_path, {"a": {"bad": value}})
    code, out = invoke(capsys, "update", str(report))
    assert code == 1
    assert "bad" in out


@pytest.mark.parametrize("key", ["Lag", "lag_up", "1lag", "lag up", ""])
def test_キーは小文字で始まり_小文字と数字とハイフンだけにする(tmp_path, capsys, key):
    report = make_report(tmp_path, {"a": {key: "1"}})
    code, out = invoke(capsys, "update", str(report))
    assert code == 1
    assert "key" in out


def test_同じキーを2つのコマンドが出したら_両方を示して止まる(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"x": "1"}, "b": {"x": "2"}})
    code, out = invoke(capsys, "update", str(report))
    assert code == 1
    assert "data/a.json" in out and "data/b.json" in out


def test_コマンドが失敗したら_コマンドと標準エラーを示して止まる(tmp_path, capsys):
    write_spec(tmp_path, [{"run": "echo boom >&2; exit 3"}])
    code, out = invoke(capsys, "update", str(tmp_path))
    assert code == 1
    assert "exit 3" in out and "boom" in out


@pytest.mark.parametrize("stdout", ["not json", "[1, 2]"])
def test_標準出力が_JSON_のオブジェクトでなければ_先頭を示して止まる(tmp_path, capsys, stdout):
    write_spec(tmp_path, [{"run": f"echo {shlex.quote(stdout)}"}])
    code, out = invoke(capsys, "update", str(tmp_path))
    assert code == 1
    assert stdout in out


def test_check_は値が変わっていなければ通る(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"x": "1"}}, tex="\\fact{x}\n")
    invoke(capsys, "update", str(report))
    code, _ = invoke(capsys, "check", str(report))
    assert code == 0


def test_check_は変わった値と_それを引用する行を示して落ち_facts_tex_は書き換えない(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"lag-up": "267〜333"}}, tex="前置き\n遅れは \\fact{lag-up} ms だった。\n")
    invoke(capsys, "update", str(report))
    before = (report / "facts.tex").read_text(encoding="utf-8")
    write_data(report, "a", {"lag-up": "300"})
    code, out = invoke(capsys, "check", str(report))
    assert code == 1
    assert "lag-up" in out and "267〜333" in out and "300" in out
    assert "paper.tex:2" in out
    assert (report / "facts.tex").read_text(encoding="utf-8") == before


def test_check_は足されたキーと消えたキーを示して落ちる(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"old": "1"}})
    invoke(capsys, "update", str(report))
    write_data(report, "a", {"new": "2"})
    code, out = invoke(capsys, "check", str(report))
    assert code == 1
    assert "added new" in out and "removed old" in out


def test_update_は変わった値と_それを引用する行を示す(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"x": "1"}}, tex="\\fact{x}\n")
    invoke(capsys, "update", str(report))
    write_data(report, "a", {"x": "2"})
    code, out = invoke(capsys, "update", str(report))
    assert code == 0
    assert "changed x" in out and "paper.tex:1" in out
    assert factdefs(report) == ["\\factdef{x}{2}"]


def test_必要なデータが無いコマンドは飛ばし_書いてある値を残す(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"x": "1"}, "b": {"y": "2"}}, tex="\\fact{x} \\fact{y}\n")
    invoke(capsys, "update", str(report))
    (report / "data" / "b.json").unlink()
    code, out = invoke(capsys, "check", str(report))
    assert code == 0
    assert "skipped" in out and "data/b.json" in out
    assert invoke(capsys, "update", str(report))[0] == 0
    assert "\\factdef{y}{2}" in factdefs(report)


def test_本文が_facts_tex_に無いキーを引用したら_場所を示して止まる(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"x": "1"}}, tex="\\fact{nope}\n")
    code, out = invoke(capsys, "update", str(report))
    assert code == 1
    assert "nope" in out and "paper.tex:1" in out
    code, out = invoke(capsys, "check", str(report))
    assert code == 1
    assert "nope" in out


def test_コメントの中の_fact_は引用に数えない(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"x": "1"}}, tex="% \\fact{nope}\n\\fact{x} は 50\\% % \\fact{nope}\n")
    code, _ = invoke(capsys, "update", str(report))
    assert code == 0


def test_code_の中の_fact_は字面のまま組まれるので_場所を示して止まる(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"x": "1"}}, tex="\\fact{x}\n識別子 \\code{run_\\fact{x}} の後ろ\n")
    code, out = invoke(capsys, "update", str(report))
    assert code == 1
    assert "\\code" in out and "paper.tex:2" in out
    code, out = invoke(capsys, "check", str(report))
    assert code == 1


def test_使われていないキーは知らせるが止めない(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"x": "1"}})
    code, out = invoke(capsys, "update", str(report))
    assert code == 0
    assert "unused: x" in out


def test_facts_tex_が無いまま_check_すると_update_を促す(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"x": "1"}})
    code, out = invoke(capsys, "check", str(report))
    assert code == 1
    assert "update" in out


def test_facts_json_が無ければ使い方の誤りとして止まる(tmp_path, capsys):
    code, out = invoke(capsys, "check", str(tmp_path))
    assert code == 2
    assert "facts.json" in out


def test_build_sh_は値がずれていたら_tectonic_の前に止まる(tmp_path, capsys):
    report = tmp_path / "r"
    report.mkdir()
    make_report(report, {"a": {"x": "1"}}, tex="\\fact{x}\n")
    invoke(capsys, "update", str(report))
    write_data(report, "a", {"x": "2"})
    result = subprocess.run(
        ["bash", str(HERE / "build.sh"), "paper.tex", str(tmp_path / "pages")],
        cwd=report,
        capture_output=True,
        text=True,
        check=False,
    )
    out = result.stdout + result.stderr
    assert result.returncode != 0
    assert "changed x" in out and "facts.py update" in out
    assert not (report / "paper.pdf").exists()


def test_build_sh_の_no_facts_は照合を飛ばす(tmp_path, capsys):
    report = tmp_path / "r"
    report.mkdir()
    make_report(report, {"a": {"x": "1"}}, tex="\\fact{x}\n")
    invoke(capsys, "update", str(report))
    write_data(report, "a", {"x": "2"})
    result = subprocess.run(
        ["bash", str(HERE / "build.sh"), "--no-facts", "paper.tex", str(tmp_path / "pages")],
        cwd=report,
        capture_output=True,
        text=True,
        check=False,
    )
    out = result.stdout + result.stderr
    assert "facts: skipped (--no-facts)" in out
    assert "changed x" not in out


needs_tectonic = pytest.mark.skipif(
    shutil.which("tectonic") is None or sys.platform != "darwin",
    reason="テンプレートのビルドには tectonic と macOS のヒラギノが要る",
)

BODY = r"""\begin{document}
\section{遅れは \fact{lag} ms}
本文の遅れは \fact{lag} ms で、差は \fact{share} だった。
\begin{table}[h]
\caption{肩の遅れは \fact{rate} ms}
\begin{tabular}{lS[table-format=3.1]}
\toprule
{関節} & {遅れ} \\
\midrule
肩 & \fact{rate} \\
肘 & 12.5 \\
\bottomrule
\end{tabular}
\end{table}
\begin{tikzpicture}
\begin{axis}[width=5cm,height=4cm]
\addplot coordinates {(0,\fact{rate}) (1,12.5)};
\end{axis}
\end{tikzpicture}
\end{document}
"""


def preamble() -> str:
    text = TEMPLATE.read_text(encoding="utf-8")
    return text[: text.index("\\begin{document}")]


@needs_tectonic
def test_テンプレートの前置きで_fact_が本文と見出しと表題と_S_列とグラフに入る(tmp_path, capsys):
    report = make_report(tmp_path, {"a": {"lag": "267〜333", "share": "12 %", "rate": "100.5"}}, tex=preamble() + BODY)
    assert invoke(capsys, "update", str(report))[0] == 0
    result = subprocess.run(
        ["tectonic", "-X", "compile", "paper.tex"], cwd=report, capture_output=True, text=True, check=False
    )
    assert result.returncode == 0, result.stderr[-3000:]
    if shutil.which("pdftotext"):
        text = subprocess.run(
            ["pdftotext", "paper.pdf", "-"], cwd=report, capture_output=True, text=True, check=False
        ).stdout
        assert "267" in text and "333" in text and "100.5" in text and "%" in text


@needs_tectonic
def test_facts_tex_に無いキーを引用すると_ビルドが落ちる(tmp_path, capsys):
    tex = preamble() + "\\begin{document}\n遅れは \\fact{nope} ms。\n\\end{document}\n"
    report = make_report(tmp_path, {"a": {"x": "1"}}, tex=tex)
    invoke(capsys, "update", str(report))
    result = subprocess.run(
        ["tectonic", "-X", "compile", "paper.tex"], cwd=report, capture_output=True, text=True, check=False
    )
    assert result.returncode != 0
    assert "Undefined fact" in result.stdout + result.stderr
