#!/usr/bin/env python3
"""Keep the numbers in a paper-report .tex in step with the scripts that compute them.

    facts.py update <report-dir>   run the commands in facts.json and write facts.tex
    facts.py check <report-dir>    run them again and fail when a value differs from facts.tex

facts.json beside the .tex lists the commands, {"commands": [{"run": "...", "requires": [...]}]}.
Each command prints one JSON object on stdout, {"key": "value", ...}, and runs through bash in
the report directory (or in its "cwd", relative to the report directory).
update writes facts.tex: one \\factdef{key}{value} per line, grouped under a "% run:" line that
names the command. The .tex quotes a value with \\fact{key}.

A command whose "requires" paths (relative to the report directory) are missing is skipped, and
the values it wrote before are kept, so a report whose raw data lives on one machine still builds
on another.

Both modes print each changed, added, or removed key with the .tex lines that quote it.
A number can change while the sentence around it ("about three times slower") no longer holds,
so reread those lines after an update.

Exit status: 0 when the values match (check) or were written (update); 1 when a value differs,
a command fails, a value cannot be typeset, or the .tex quotes a key that facts.tex lacks;
2 on a usage error.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from pathlib import Path

SPEC = "facts.json"
OUTPUT = "facts.tex"
GENERATED = "% Generated by facts.py from facts.json. Do not edit by hand; run facts.py update.\n"
RUN_PREFIX = "% run: "
KEY = re.compile(r"[a-z][a-z0-9-]*")
# These specials typeset once escaped. The others would turn a value into markup, so they are rejected
ESCAPES = {"%": r"\%", "#": r"\#", "&": r"\&", "$": r"\$", "_": r"\_"}
FORBIDDEN = "\\{}~^\n\r"
UNESCAPE = re.compile(r"\\([%#&$_])")
FACTDEF = re.compile(r"\\factdef\{([^}]*)\}\{(.*)\}$")
USE = re.compile(r"\\fact\{([^}]*)\}")
# \code{} takes its argument as url-style verbatim, so a \fact inside it prints as written
IN_CODE = re.compile(r"\\code\{[^{}]*\\fact\{")
COMMENT = re.compile(r"(?<!\\)%.*")
HEAD = 200  # characters of unparsable output to show


class FactsError(Exception):
    """A problem the writer must fix before the values can be used."""


@dataclass(frozen=True)
class Command:
    run: str
    cwd: str = "."
    requires: tuple[str, ...] = ()


@dataclass(frozen=True)
class Fact:
    value: str  # escaped for TeX, as written to facts.tex
    run: str  # the command that printed it


def load_spec(report: Path) -> list[Command]:
    """Read facts.json. A run string is also a line in facts.tex, so it must be one line."""
    data = json.loads((report / SPEC).read_text(encoding="utf-8"))
    entries = data.get("commands") if isinstance(data, dict) else None
    if not isinstance(entries, list):
        raise FactsError(f'{SPEC} must be an object with a "commands" list')
    commands = []
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("run"), str) or "\n" in entry["run"]:
            raise FactsError(f'each command in {SPEC} needs a one-line "run" string: {entry!r}')
        commands.append(Command(entry["run"], entry.get("cwd", "."), tuple(entry.get("requires", []))))
    return commands


def escape(key: str, value: object, run: str) -> str:
    """Return the value as TeX text, or raise when it cannot be typeset as plain text."""
    if isinstance(value, bool) or not isinstance(value, (str, int, float)):
        raise FactsError(f"{key}: value must be a string or a number, not {value!r} (from: {run})")
    text = str(value)
    bad = sorted({char for char in text if char in FORBIDDEN})
    if bad:
        raise FactsError(f"{key}: value {text!r} contains {''.join(bad)!r}; print plain text (from: {run})")
    return "".join(ESCAPES.get(char, char) for char in text)


def plain(value: str | None) -> str:
    return UNESCAPE.sub(r"\1", value or "")


def parse_output(stdout: str, run: str) -> dict[str, str]:
    try:
        data = json.loads(stdout)
    except json.JSONDecodeError:
        data = None
    if not isinstance(data, dict):
        raise FactsError(f"stdout is not one JSON object (from: {run}): {stdout.strip()[:HEAD]!r}")
    facts = {}
    for key, value in data.items():
        if not KEY.fullmatch(key):
            raise FactsError(f"key {key!r} must start with a-z and use only a-z, 0-9, and '-' (from: {run})")
        facts[key] = escape(key, value, run)
    return facts


def run_command(command: Command, report: Path) -> dict[str, str]:
    """Run one command and return its values. Side effect: whatever the command does."""
    result = subprocess.run(
        ["bash", "-c", command.run],
        cwd=report / command.cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if result.returncode != 0:
        raise FactsError(
            f"command failed with exit {result.returncode}: {command.run}\n{result.stderr.strip()[-1000:]}"
        )
    return parse_output(result.stdout, command.run)


def missing(command: Command, report: Path) -> list[str]:
    return [path for path in command.requires if not (report / Path(path).expanduser()).exists()]


def read_committed(path: Path) -> dict[str, Fact]:
    facts: dict[str, Fact] = {}
    run = ""
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(RUN_PREFIX):
            run = line[len(RUN_PREFIX) :]
        elif match := FACTDEF.match(line):
            facts[match.group(1)] = Fact(match.group(2), run)
    return facts


def collect(report: Path, commands: list[Command], committed: dict[str, Fact]) -> tuple[dict[str, Fact], list[str]]:
    """Run every command whose data is present; keep the committed values of the others."""
    facts: dict[str, Fact] = {}
    notes: list[str] = []
    for command in commands:
        absent = missing(command, report)
        if absent:
            produced = {key: fact for key, fact in committed.items() if fact.run == command.run}
            notes.append(f"skipped (missing {', '.join(absent)}), kept {len(produced)} keys: {command.run}")
        else:
            produced = {key: Fact(value, command.run) for key, value in run_command(command, report).items()}
        for key, fact in produced.items():
            if key in facts:
                raise FactsError(f"key {key!r} is printed by two commands:\n  {facts[key].run}\n  {command.run}")
            facts[key] = fact
    return facts, notes


def render(facts: dict[str, Fact], commands: list[Command]) -> str:
    parts = [GENERATED]
    for command in commands:
        keys = sorted(key for key, fact in facts.items() if fact.run == command.run)
        if keys:
            parts.append(f"\n{RUN_PREFIX}{command.run}\n")
            parts.extend(f"\\factdef{{{key}}}{{{facts[key].value}}}\n" for key in keys)
    return "".join(parts)


def tex_lines(report: Path) -> Iterator[tuple[str, str]]:
    """Yield (file:line, text without comments) for every .tex line in the report except facts.tex."""
    for tex in sorted(report.rglob("*.tex")):
        relative = tex.relative_to(report)
        if relative == Path(OUTPUT) or any(part.startswith(".") for part in relative.parts):
            continue
        for number, line in enumerate(tex.read_text(encoding="utf-8").splitlines(), 1):
            yield f"{relative}:{number}", COMMENT.sub("", line)


def find_uses(lines: Iterable[tuple[str, str]]) -> dict[str, list[str]]:
    """Map each key quoted with \\fact to its places."""
    uses: dict[str, list[str]] = {}
    for place, text in lines:
        for key in USE.findall(text):
            uses.setdefault(key, []).append(place)
    return uses


def find_in_code(lines: Iterable[tuple[str, str]]) -> list[str]:
    return [place for place, text in lines if IN_CODE.search(text)]


def compare(old: dict[str, Fact], new: dict[str, Fact]) -> list[tuple[str, str | None, str | None]]:
    changes = []
    for key in sorted(old.keys() | new.keys()):
        before = old[key].value if key in old else None
        after = new[key].value if key in new else None
        if before != after:
            changes.append((key, before, after))
    return changes


def describe(changes: list[tuple[str, str | None, str | None]], uses: dict[str, list[str]]) -> list[str]:
    lines = []
    for key, before, after in changes:
        if before is None:
            lines.append(f"facts: added {key} = {plain(after)}")
        elif after is None:
            lines.append(f"facts: removed {key} (was {plain(before)})")
        else:
            lines.append(f"facts: changed {key}: {plain(before)} -> {plain(after)}")
        if key in uses:
            lines.append(f"  used at {', '.join(uses[key])}")
    return lines


def main(argv: list[str]) -> int:
    if len(argv) != 3 or argv[1] not in ("update", "check"):
        print(__doc__, file=sys.stderr)
        return 2
    mode, report = argv[1], Path(argv[2])
    if not (report / SPEC).is_file():
        print(f"facts: no {SPEC} in {report}", file=sys.stderr)
        return 2
    output = report / OUTPUT
    if mode == "check" and not output.is_file():
        print(f"facts: {OUTPUT} is missing; run 'facts.py update {report}' first")
        return 1
    committed = read_committed(output) if output.is_file() else {}
    try:
        commands = load_spec(report)
        facts, notes = collect(report, commands, committed)
    except FactsError as error:
        print(f"facts: {error}")
        return 1

    lines = list(tex_lines(report))
    uses = find_uses(lines)
    in_code = find_in_code(lines)
    changes = compare(committed, facts)
    undefined = {key: places for key, places in uses.items() if key not in facts}
    unused = sorted(key for key in facts if key not in uses)
    for note in notes:
        print(f"facts: {note}")
    # On the first update every key is new, and listing them all says nothing
    if committed or mode == "check":
        for line in describe(changes, uses):
            print(line)
    for key, places in sorted(undefined.items()):
        print(f"facts: undefined {key} at {', '.join(places)}")
    if in_code:
        print(f"facts: \\fact inside \\code{{}} prints as written, not as the value, at {', '.join(in_code)}")
    if unused:
        print(f"facts: unused: {', '.join(unused)}")

    if mode == "update":
        output.write_text(render(facts, commands), encoding="utf-8")
        print(f"facts: wrote {len(facts)} keys to {output}")
        return 1 if undefined or in_code else 0
    if changes or undefined or in_code:
        if changes:
            print(f"facts: run 'facts.py update {report}', then reread the lines listed above")
        return 1
    print(f"facts: ok ({len(facts)} keys)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
